server:
  port: 8888

spring:
  application:
    name: config-server
  config:
    use-legacy-processing: true
  security:
    user:
      name: config-user
      password: ${CONFIG_SERVER_PASSWORD:dev}
