config-repo-path: file:///Users/vladimir.perfilev/Projects/Private/Fatodo/apps/fatodo-config-repo

spring:
  profiles:
    include: native

  cloud:
    config:
      server:
        native:
          searchLocations: ${config-repo-path}, ${config-repo-path}/{application}
