config-repo-path: git@gitlab.com:fatodo/fatodo-config-repo

spring:
  cloud:
    config:
      server:
        git:
          uri: ${config-repo-path}
          searchPaths: '{application}'
          defaultLabel: 'master'
