config-repo-path: git@gitlab.com:fatodo/fatodo-config-repo

spring:
  cloud:
    config:
      server:
        git:
          uri: ${config-repo-path}
          searchPaths: '{application}'
          ignoreLocalSshSettings: true
          strictHostKeyChecking: false
          hostKey: AAAAB3NzaC1yc2EAAAADAQABAAACAQDR1hF9zwKpohwS/8vGgWGZixgpKYdAfEJMguZVgvakKPHJE8rZPzZ+d7s1hc9CtD37ipkaguf5ShxJe4iTh0t7691JEdFq/m8ARSJNnri8mnWrkxSF406WtUdoDno2gZ4wGj1xLFSjaS2LaMyYVYmr9szBnbPjBxi3+oYczUgT8r+ucuIHzAM8Aernm3F2yc2vBrxbBRogWY+V43A0U7qTWLpQq9OrOIzJ0ecSMcYBCBPfKxnbi4lakNoa3P2SwlocywM2u3ivWEuNmON2X0hWdirrvPjSkUCvr8lufAr2ud4eoXXKYMlMA0f56DONzZOmd/bf0u/5PiJ/0hEp0w2OKdpmBp9raxhLntJC0U/ejOZ/5E2yswZIiD0OUll3YYenTPUCTzDevtI0l645yYKLMLhvWKh2NYJeD4HnDVrtEcKzTL8gkDMNTkpkdbMN/3NtuZq6K9KBHf6wIANaONav+JPS0jT7uYr/s1Py0E29lu7Kh/8+jVWvvvXgPB5O1xmo4ioHT59qOWOS6GWua2+K4DgWFJln9hOh5/Umb5uvYsVGa6Me7nMc84SCAG6BQ7EjAWT5SSm6JLL1R+RaxrT5HQvTwjTG9YgB868iuPkvLbdQE1DDYf8A1YsOdVLmPHxIXZmTqF+Cqe199py54wmKyGr+J+ovxrNfJL1VPH0Sxw==
          hostKeyAlgorithm: ssh-rsa
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKgIBAAKCAgEA0dYRfc8CqaIcEv/LxoFhmYsYKSmHQHxCTILmVYL2pCjxyRPK
            2T82fne7NYXPQrQ9+4qZGoLn+UocSXuIk4dLe+vdSRHRav5vAEUiTZ64vJp1q5MU
            heNOlrVHaA56NoGeMBo9cSxUo2kti2jMmFWJq/bMwZ2z4wcYt/qGHM1IE/K/rnLi
            B8wDPAHq55txdsnNrwa8WwUaIFmPleNwNFO6k1i6UKvTqziMydHnEjHGAQgT3ysZ
            24uJWpDaGtz9ksJaHMsDNrt4r1hLjZjjdl9IVnYq67z40pFAr6/JbnwK9rneHqF1
            ymDJTANH+egzjc2Tpnf239Lv+T4if9IRKdMNjinaZgafa2sYS57SQtFP3ozmf+RN
            srMGSIg9DlJZd2GHp0z1Ak8w3r7SNJeuOcmCizC4b1iodjWCXg+B5w1a7RHCs0y/
            IJAzDU5KZHWzDf9zbbmauivSgR3+sCADWjjWr/iT0tI0+7mK/7NT8tBNvZbuyof/
            Po1Vr7714DweTtcZqOIqB0+fajljkuhlrmtviuA4FhSZZ/YToef1Jm+br2LFRmuj
            Hu5zHPOEggBugUOxIwFk+UkpuiSy9UfkWsa0+R0L08I0xvWIAfOvIrj5Ly23UBNQ
            w2H/ANWLDnVS5jx8SF2Zk6hfgqntffacueMJishq/ifqL8azXyS9VTx9EscCAwEA
            AQKCAgEAhl0J9EJTFSYtzeinpmOAiJ4tiWYDKkKm/XEwZn8mybVCJZyb3oKAtXib
            ksktDyx1KBX2tagvPEy9UjxdFwKiTiaZGsnjDB0CHO0n6wYAixxozsWudZE46H4J
            zFLA5RgYn/qdb1OQmtaliEhCAiV7s3akZDJEVtJbfKtZpyW3yrY9EUqU+6MiSxF7
            RnUdsY/FOhcZEztwIFjY/YSWe5tFtEYzf6aXMmNSm4Th7p+ah1yRxOxHcXKnMCvi
            zSLG6Gu04g0I8MoYnEbwkindNRYMLvkZwLvPpJ3ICveIB0w8hQI9feWrlDxniVns
            g9Sw9lM2AXl9xpK+gR3NX4W24c44NbA16a1saS91IKqNmOyTPRGGrph3tu8d3ZSc
            +CndW5QN3liGrpVNpJ5XvV1JHnDS+I69car6ohSWpim7Us5zbQtOck16gEviWImU
            CthvPfjB6VbnYraeQEHS/R1UYCotc/6bA95a7IZS3tUpZaQD5f7HZCZ3shmdEvc2
            zYugM7RfFFGSHdRIDB6169XjAdGZTFMIdUSmTY7UQarqn5QWgdX02r7ITi041yq4
            NLfn289AIVLDQUOaAldCBI1BeN7sA3SKHmkckr2CJN1nMQRRZuskLduggjvEFUYt
            fbfSVsKK57pZX6YS2XVnp+OzsV/8Z7smoBNyWXwU29qp7C+/orkCggEBAOpQw4fr
            UHl+bSRXIFqBc18ed/ZR5SCcrh7deRRpKcu08r7CFVbGfIIBaFhSokkcZ1PfJa0p
            3OZ6SLFL07U84Dw+ynVWVNqfC8i8KxUVHsIJixrSJ1BMRx+fRtXZ4X1Av9T9dazA
            +uudYUdSaqDYZm8U26lmkZ00nLIpnj92nAuQAgjQZMydoBMm7UNmTRQ6ejWiqgjJ
            nACBWPelirFbENF4ZnN/ACFQc9mHIgQ+3IN1Uifomwz3AsKZc8vF7pHE1ITsdbKy
            mUuOYv0qJAN0gYGGU9uI0z4ghzhR/aIGNv2/Z4WOa4nI8pVOJ6UI7HdswHqQ7I0i
            JMkjSUxOUNDqP40CggEBAOVBW9t1WPduWT5GetahEjBTpGbm/HwDayS1/UJxkoER
            Kf8XYD39BIS2OgQ7AvvE9g6gnQD5+82b2mNFgx8s8bByXH3miXUbJNABpt6CPJFM
            wv9PgL7iLvz69rlFMD7P4kp6EuKD/JmK1dr2nRUjZp84VHPzlc2/KSTC6E2xeze3
            TWbyud4RNwRl7kIApRGexZ5ACkT/rUeqIldGylbVSOK/YTaCroDc61dsfugt/GsA
            FYWC6FEaLNMw+ZL4colZUohJ57/hkFxOdkIe1h7Zl+vx+ZofPyfpYEcmGCf0D8b8
            A9V02EUHgcxTqTB5NF2A9lnkRfHnU2ee9VPZwvjMDKMCggEBAMA4Px+KgDsa5ugv
            /V+h4IaAlULhzgih4Al8AG8pEluFdrnct+q2678u7m2+ZFl7zpw0bFERDaGZYXbo
            0KVWalGh5S67AuNSJDWpf+JMsC3X7GC1VAEAgjxDyrV2hw/chUJyJw3wRifxtLLw
            vn5y6B1qTAU9GmmPlphloedIIx0tJy4Z3wcoq//qKCvpiYP1sPm9FqYc1jhn5BdM
            m2mBXluo3MsUvYOW32LtA4/eDcJeBWat4DyTipUfk6nwFxVIFltxK+DLuQwNo9Ex
            t9eJxQ//pV1scnb98k/Wmy5G0Of7FC6xNjETQ0YOlmFB39LcyU4DA7uH7gt/Qgsy
            GAQ6lqUCggEAGK7AxRANVBZ9ZUcRUqpk2u8mdC3KYU+86WburYiszVibvOs3YXUs
            V12HQY1Y9OJv24NPZBuGEM0G5klFpMWh/+1QJ/36LrGNdRe4b5x2CO7Kz9Ivel2/
            0Vzz016voxOeuYYLIngzahSYkcqbfvsgwWO/M/y11EEQnPSfLj49lfIWU08u08nm
            soKG9HQ9UXhWroMWl/cvINggemUUw+SSxFb2kHfhcd5XOEJmJ3lMA/kuWAGQIas/
            yD0tobU+H6uORz4txWrzr/yCnvvS8d9bi/uxc/aJRjLKOt7PGv4b9MCNaR37avMz
            9lvLi3yBNs/7thHtte3B/RYQM8buRvsxIQKCAQEAlnpwCiBGLVo9vk13Tb4XKzjk
            R3iYGGHpSgfotN2DOKA4nhEBWINrDVH0/JlLg6tLPaSLkrc64iKIjWefU1K/dDNM
            NlAVifIe599TBzdDCvxsnNzmEqSqh6tdo1si6N+r8mjmqI4cKK/A22DsZPI58MfR
            9aGGUiE0g1u3gwDN1P8WmPPcQJsS6Ky5g6cB9eH9vbU41xbqNutoXdDcJiJndYmI
            5AJCGsHOzEtDdoZSbiKo0Ytz/kjcSqKiH4iAKbVfofD5V+t5M+kft+c6FCLHtD1g
            yvzNOWDekq8qShQD0V8NDTqNDOTJ3fq0q08b9oKcdzeg/74HvR6DtjiGFGPO2g==
            -----END RSA PRIVATE KEY-----
