server:
  port: 4000


# Gateway config
zuul:
  sensitiveHeaders: Authorization
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:

    test-service:
      path: /api/test/**
      serviceId: test-service
      stripPrefix: true
      sensitiveHeaders:

    oauth2-service:
      path: /api/oauth2/**
      serviceId: auth-service
      stripPrefix: false
      sensitiveHeaders:

    auth-service:
      path: /api/auth/**
      serviceId: auth-service
      stripPrefix: true
      sensitiveHeaders:

# Hystrix and Ribbon
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
